vars:
  - "D0_M" 
  - "Dstarp_Q"
  - "D0_cosHel_0"
  - "Dstarp_CMS_p"
  - "gamma_E"
  - "gamma_CMS_E"
  - "gamma_clusterSecondMoment"
  - "gamma_genMotherID"
  - "gamma_genMotherPDG"
  - "__ncandidates__"
  - "__experiment__"
  - "__run__"
  - "__event__"
  - "Dstarp_isSignal"
  - "D0_isSignal"
  - "Pi0_Prob"
  - "Pi0_Prob_50MeV"
  - "Pi0_Prob_75MeV"  
  - "Pi0_Prob_100MeV"
  - "Pi0_Prob_125MeV"
  - "Pi0_Prob_150MeV"  
  - "Eta_Prob"
  - "Eta_Prob_50MeV"
  - "Eta_Prob_75MeV"
  - "Eta_Prob_100MeV"
  - "Eta_Prob_125MeV"
  - "Eta_Prob_150MeV"
  - "Eta_Prob_175MeV"
  - "Eta_Prob_200MeV"
  - "ROE_Pi0_InvM"
  - "ROE_Pi0_InvM_50MeV"
  - "ROE_Pi0_InvM_75MeV"
  - "ROE_Pi0_InvM_100MeV"
  - "ROE_Pi0_InvM_125MeV"
  - "ROE_Pi0_InvM_150MeV"
  - "ROE_Eta_InvM"
  - "ROE_Eta_InvM_50MeV"
  - "ROE_Eta_InvM_75MeV"
  - "ROE_Eta_InvM_100MeV"
  - "ROE_Eta_InvM_125MeV"
  - "ROE_Eta_InvM_150MeV"
  - "ROE_Eta_InvM_175MeV"
  - "ROE_Eta_InvM_200MeV"
  - "Pi0_soft_genMotherPDG"
  - "Pi0_soft_genMotherPDG_50MeV"
  - "Pi0_soft_genMotherPDG_75MeV"
  - "Pi0_soft_genMotherPDG_100MeV"
  - "Pi0_soft_genMotherPDG_125MeV"
  - "Pi0_soft_genMotherPDG_150MeV"
  - "Eta_soft_genMotherPDG"
  - "Eta_soft_genMotherPDG_50MeV"
  - "Eta_soft_genMotherPDG_75MeV"
  - "Eta_soft_genMotherPDG_100MeV"
  - "Eta_soft_genMotherPDG_125MeV"
  - "Eta_soft_genMotherPDG_150MeV"
  - "Eta_soft_genMotherPDG_175MeV"
  - "Eta_soft_genMotherPDG_200MeV"
  - "Pi0_soft_genMotherID"
  - "Pi0_soft_genMotherID_50MeV"
  - "Pi0_soft_genMotherID_75MeV"
  - "Pi0_soft_genMotherID_100MeV"
  - "Pi0_soft_genMotherID_125MeV"
  - "Pi0_soft_genMotherID_150MeV"
  - "Eta_soft_genMotherID"
  - "Eta_soft_genMotherID_50MeV"
  - "Eta_soft_genMotherID_75MeV"
  - "Eta_soft_genMotherID_100MeV"
  - "Eta_soft_genMotherID_125MeV"
  - "Eta_soft_genMotherID_150MeV"
  - "Eta_soft_genMotherID_175MeV"
  - "Eta_soft_genMotherID_200MeV"
  - "Pi0_soft_E"
  - "Pi0_soft_E_50MeV"
  - "Pi0_soft_E_75MeV"
  - "Pi0_soft_E_100MeV"
  - "Pi0_soft_E_125MeV"
  - "Pi0_soft_E_150MeV"
  - "Eta_soft_E"
  - "Eta_soft_E_50MeV"
  - "Eta_soft_E_75MeV"
  - "Eta_soft_E_100MeV"
  - "Eta_soft_E_125MeV"
  - "Eta_soft_E_150MeV"
  - "Eta_soft_E_175MeV"
  - "Eta_soft_E_200MeV"
  