vars:
  - "D0_M" 
  - "Dstarp_Q"
  - "D0_cosHel_0"
  - "Dstarp_CMS_p"
  - "gamma_E"
  - "gamma_clusterSecondMoment"
  - "__ncandidates__"
  - "__experiment__"
  - "__run__"
  - "__event__"
  - "Dstarp_isSignal"
  - "D0_isSignal"
