name:
  D0_M: "M(D^0)"
  Dstarp_Q: "Q"
  D0_cosHel_0: "mathrm{cos}Hel_0"
  Dstarp_CMS_p: "P_{D^{*+}_{CMS}}"
  gamma_E: "E_{gamma}"
  gamma_clusterSecondMoment: "clusterSecondmoment(gamma)"
  __ncandidates__: "ncandidiates"
  __experiment__: "experiment"
  __run__: "run"
  __event__: "event"
  Dstarp_isSignal: "Dstarp isSignal"
  D0_isSignal: "D0 isSignal"
  Phi_InvM : "M(/phi)"
  Rho_InvM : "M(/rho^0)"
  antiKstar_InvM : "M(/bar{K}^{*0})"
  Omega_InvM : "M(/omega)"
  gamma_CMS_E : "E_{CMS}(gamma)"
  gamma_genMotherID : "gamma_genMotherID"
  gamma_genMotherPDG : "gamma_genMotherPDG"
  
  Pi0_Prob : ""
units:
  D0_M: "mathrm{GeV}"
  Dstarp_Q: "mathrm{GeV}"
  D0_cosHel_0: ""
  Dstarp_CMS_p: "mathrm{GeV}"
  gamma_E: "mathrm{GeV}"
  gamma_clusterSecondMoment: ""
  __ncandidates__: ""
  __experiment__: ""
  __run__: ""
  __event__: ""
  Dstarp_isSignal: ""
  D0_isSignal: ""
  Phi_InvM : "mathrm{GeV}"
  Rho_InvM : "mathrm{GeV}"
  antiKstar_InvM : "mathrm{GeV}"
  Omega_InvM : "mathrm{GeV}"
  gamma_CMS_E : "mathrm{GeV}"
  gamma_genMotherID : ""
  gamma_genMotherPDG : ""
  Pi0_Prob : ""
